### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by AckonSamuel** [Nemwel-Boniface/spacetravellers#49]
Hello,
Here is the [project link](https://github.com/Nemwel-Boniface/spacetravellers/projects/1)

There are two people on the team.

Happy reviewing. 🐥

**Comment by Kingstalux** [comment]
Hi @AckonSamuel and @Nemwel-Boniface , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Good job distributing the cards


## Required Changes ♻️
- [ ] Kindly provide the link to the project itself ([link](https://github.com/Nemwel-Boniface/spacetravellers/projects/1)) and not the repo 👍 . 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nemwel-Boniface** [comment]
Hello, @Kingstalux  Thank you for the review. 
I have updated  the link to the project [here](https://github.com/Nemwel-Boniface/spacetravellers/projects/1)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @AckonSamuel and @Nemwel-Boniface,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
